---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: set the hostname for the machine
    hostname: name={{hostname}}
  - name: enable multilib
    blockinfile:
      dest: /etc/pacman.conf
      block: |
        [multilib]
        Include = /etc/pacman.d/mirrorlist
